version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: si_releves_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: si_releves_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog
    container_name: si_releves_mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI

  backend:
    build: ./backend
    container_name: si_releves_backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: si_releves_db
      DB_USER: root
      DB_PASSWORD: root
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
    depends_on:
      - db
      - mailhog

  frontend:
    build: ./frontend
    container_name: si_releves_frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  db_data:


