services:
  db:
    image: mysql:8.0
    container_name: si_releves_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: si_releves_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog
    container_name: si_releves_mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI

  backend:
    build: ./backend
    container_name: si_releves_backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: si_releves_db
      DB_USER: root
      DB_PASSWORD: root
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      SEED_ON_START: true
    depends_on:
      - db
      - mailhog

  simulator:
    build: ./backend
    container_name: si_releves_simulator
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: si_releves_db
      DB_USER: root
      DB_PASSWORD: root
      SIM_API_URL: http://backend:3000/api
    depends_on:
      - db
      - backend
    command: ["npm", "run", "simulate"]

  frontend:
    build: ./frontend
    container_name: si_releves_frontend
    depends_on:
      - backend

  nginx:
    build:
      context: ./backend
      dockerfile: Dockerfile.nginx
    container_name: si_releves_nginx
    depends_on:
      - frontend
      - backend
    ports:
      - "4200:443"

volumes:
  db_data:



